### ISSUE TITLE
Remove build configuration cache warning

### ISSUE THREAD

**Issue by koppor** [petr-panteleyev/jpackage-gradle-plugin#40]
When using this plugin we get following output:

```
Caching disabled for task ':jabsrv-cli:jpackage' because:
  Caching has not been enabled for the task
Task ':jabsrv-cli:jpackage' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
```

Maybe, this can be avoided when declaring `destination` as file output?

(This refs #27)

**Comment by petr-panteleyev** [comment]
Plugin uses ```getProject()``` to get toolchain extension. I'm not sure how to avoid this which makes configuration cache inaccessible even if I get rid of other ```getProject()``` usages.

As for ```destination``` as file output, maybe this can be done though it's basically useless. Each invocation of jpackage must run on empty ```destination``` otherwise jpackage tool itself will fail. So either you run clean + jpackage or use ```removeDestination``` parameter.

**Comment by petr-panteleyev** [comment]
I've investigated a bit more on the subject. It is certainly possible to make this plugin cache configuration compatible.
I've even prototyped necessary changes.

Unfortunately, these changes are not backward compatible. All paths properties must be changed from String to File and relative paths must be resolved by build.gradle instead of plugin using ```project.file(path)```. Or just drop this convenience completely.

Honestly I'm not sure config cache is that important for this particular plugin.

**Comment by koppor** [comment]
Thank you so much for prototyping!

> Honestly I'm not sure config cache is that important for this particular plugin.

In our case caching speeds up any gradle execution by approx 5 seconds. Even on a large machine. We cannot use IntelliJs build system, because it breaks now and then with Java Modle System; gradle is more reliable.

We are evaluating several plugins and still have other options to use. Lets see. I still have the hope any of the plugins will be caching compatible 2025. 😅

**Comment by petr-panteleyev** [comment]
Ok, probably it's time to refresh this plugin a bit. No commitments on ETA though.
